<!DOCTYPE html>
<html>
<head>
    <title>Laporan Penjualan QRasa</title>
    <style>
        body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 14px; color: #000; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 15px; }
        .header h1 { margin: 0; color: #000; font-size: 24px; text-transform: uppercase; letter-spacing: 1px; }
        .header p { margin: 5px 0; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #333; padding: 10px; text-align: left; }
        th { background-color: #f2f2f2; color: #000; border-bottom: 2px solid #000; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .summary { margin-top: 30px; text-align: right; font-size: 16px; padding: 15px 0; border-top: 2px solid #000; }
        .summary strong { font-size: 16px; color: #000; }
        .footer { position: fixed; bottom: -20px; left: 0px; right: 0px; height: 30px; text-align: center; font-size: 10px; color: #666; border-top: 1px dashed #ccc; padding-top: 10px; }
    </style>
</head>
<body>
    @php $setting = \App\Models\Setting::first(); @endphp
    <div class="header">
        <h1>Laporan Rekapitulasi Penjualan</h1>
        <p><strong>{{ $setting ? $setting->store_name : 'QRasa' }}</strong></p>
        <p><strong>Periode:</strong> {{ $periodLabel }}</p>
        <p><strong>Dicetak pada:</strong> {{ $printDate }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center">No.</th>
                <th>Tanggal Pembelian</th>
                <th>ID Pesanan</th>
                <th>Meja</th>
                <th>Metode Bayar</th>
                <th class="text-right">Total Transaksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse($pesans as $index => $pesan)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $pesan->created_at->timezone('Asia/Jakarta')->format('d M Y, H:i') }} WIB</td>
                    <td>#{{ $pesan->id }}</td>
                    <td>{{ $pesan->meja ? "Meja {$pesan->meja->nomor_meja}" : 'Bawa Pulang / TA' }}</td>
                    <td>{{ strtoupper($pesan->payment_method) }}</td>
                    <td class="text-right">Rp{{ number_format($pesan->total, 0, ',', '.') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center" style="padding: 20px;">Tidak ada riwayat transaksi pada periode ini.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        Pendapatan Netto (Bersih): <strong>Rp{{ number_format($totalSubtotal, 0, ',', '.') }}</strong><br>
        Service Charge ({{ $setting ? $setting->service_percent : 5 }}%): <strong>Rp{{ number_format($totalService, 0, ',', '.') }}</strong><br>
        Pajak PB1 ({{ $setting ? $setting->tax_percent : 11 }}%): <strong>Rp{{ number_format($totalPb1, 0, ',', '.') }}</strong><br><br>
        Total Transaksi Murni: <strong>{{ $totalOrders }} bon</strong> &nbsp;&nbsp;|&nbsp;&nbsp;
        Total Pendapatan (Bruto): <strong style="font-size: 20px;">Rp{{ number_format($totalRevenue, 0, ',', '.') }}</strong>
    </div>

    <div class="footer">
        Generated by Sistem Manajemen {{ $setting ? $setting->store_name : 'QRasa' }} &copy; {{ date('Y') }}
    </div>
</body>
</html>
